AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  CDDemoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-a2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF2
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::936464305103:role/service-role/L2-role-jemiuscu"
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos-a2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF1
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::936464305103:role/service-role/L2-role-jemiuscu"
      Environment:
        Variables:
          REGION: us-east-1
